[package]
name = "uncrustify"
version = "0.81.0"
revision = "1edgeterm1"
license = "GPL-2.0-or-later"
homepage = "https://github.com/uncrustify/uncrustify"
description = "Source code formatter for multiple programming languages"
depends = []

[source]
url = "https://github.com/uncrustify/uncrustify/archive/refs/tags/uncrustify-0.81.0.tar.gz"
sha256 = "484623dc16b92206adc6ac0770077c6c67c6e441102148c2a121a19549330ff9"

[build]
system = "cmake"
pristine_source = true
configure_args = ["-DENABLE_TESTS=OFF"]
make_args = []
install_args = []
dependencies = []
pre = []
post = []
link_compat = true

[runtime]
commands = ["uncrustify"]
mode = "streaming"
capability = "full"

[tests]
smoke = ["uncrustify --version"]
