[package]
name = "sed"
version = "4.10"
revision = "1edgeterm1"
license = "GPL-3.0-or-later"
homepage = "https://www.gnu.org/software/sed/"
description = "GNU stream editor"
depends = []

[source]
url = "https://ftp.gnu.org/gnu/sed/sed-4.10.tar.xz"
sha256 = "b8e72182b2ec96a3574e2998c47b7aaa64cc20ce000d8e9ac313cc07cecf28c7"

[build]
system = "autotools"
configure_args = ["--disable-nls"]
dependencies = []
pre = []
post = []
pristine_source = true
link_compat = true

[runtime]
commands = ["sed"]
mode = "streaming"
capability = "full"

[tests]
smoke = ["sed --version","printf alpha | sed s/alpha/beta/"]
