[package]
name = "findutils"
version = "4.11.0"
revision = "1edgeterm2"
license = "GPL-3.0-or-later"
homepage = "https://www.gnu.org/software/findutils/"
description = "GNU file search utilities"
depends = []

[source]
url = "https://ftp.gnu.org/gnu/findutils/findutils-4.11.0.tar.xz"
sha256 = "bfd19cb06cc71f3352d567e90284d8cdac02ac89774bbeadf0b533b0c11432fd"

[build]
system = "autotools"
configure_args = ["--disable-nls"]
dependencies = []
pre = ["export ac_cv_func_getgroups=yes ac_cv_func_getgroups_works=yes gl_cv_func_getgroups_works=yes ac_cv_type_getgroups=gid_t"]
post = []
pristine_source = true
include_compat = true
link_compat = true

[runtime]
commands = ["find","xargs"]
mode = "streaming"
capability = "full"

[tests]
smoke = ["find --version","find . -maxdepth 0"]
