[package]
name = "tar"
version = "1.35"
revision = "1edgeterm2"
license = "GPL-3.0-or-later"
homepage = "https://www.gnu.org/software/tar/"
description = "GNU archive utility"
depends = []

[source]
url = "https://ftp.gnu.org/gnu/tar/tar-1.35.tar.gz"
sha256 = "14d55e32063ea9526e057fbf35fcabd53378e769787eff7919c3755b02d2b57e"

[build]
system = "autotools"
configure_args = ["--disable-nls"]
dependencies = []
pre = ["export ac_cv_func_getgroups=yes"]
post = []
pristine_source = true
link_compat = true
include_compat = true

[runtime]
commands = ["tar"]
mode = "streaming"
capability = "full"

[tests]
smoke = ["tar --version"]
