[package]
name = "ripgrep"
version = "15.2.0"
revision = "1edgeterm1"
license = "MIT"
homepage = "https://github.com/BurntSushi/ripgrep"
description = "Recursive regular expression search"
depends = []

[source]
url = "https://github.com/BurntSushi/ripgrep/archive/refs/tags/15.2.0.tar.gz"
sha256 = "7605249d3eb0d5f170e3414498e3344e26b1e7a147aec518b57090b80036a562"

[build]
system = "cargo"
install_args = ["install -m 755 target/wasm32-wasip1/release/rg.wasm /build/stage/usr/local/bin/rg"]
dependencies = []
pre = []
post = []

[runtime]
commands = ["rg"]
mode = "streaming"
capability = "full"

[tests]
smoke = ["rg --version"]
