[package]
name = "dash"
version = "0.5.13.5"
revision = "2edgeterm1"
license = "BSD-3-Clause"
homepage = "http://gondor.apana.org.au/~herbert/dash/"
description = "POSIX command shell"
depends = []

[source]
url = "https://cdn.netbsd.org/pub/pkgsrc/distfiles/dash-0.5.13.5.tar.gz"
sha256 = "40090101a2a491f13e901d3d48e90414f26634628b9bfff35ff540363c227a7d"

[build]
system = "autotools"
pristine_source = true
asyncify = true
asyncify_safe = true
threads = false
configure_args = []
dependencies = []
pre = ["export ac_cv_func_memfd_create=yes"]
post = []
emulated_mman = true
link_compat = true

[runtime]
commands = ["dash"]
mode = "interactive"
capability = "full"

[tests]
smoke = ["dash -c 'printf ok'"]
