[package]
name = "ncdu"
version = "1.22"
revision = "1edgeterm7"
license = "MIT"
homepage = "https://dev.yorhel.nl/ncdu"
description = "Interactive disk usage analyzer"
depends = ["ncurses"]

[source]
url = "https://dev.yorhel.nl/download/ncdu-1.22.tar.gz"
sha256 = "0ad6c096dc04d5120581104760c01b8f4e97d4191d6c9ef79654fa3c691a176b"

[build]
system = "autotools"
configure_args = ["--disable-nls"]
make_args = []
install_args = []
dependencies = ["ncurses"]
pre = ["cp /build/prefix/lib/libncursesw.a /build/prefix/lib/libncurses.a", "export CPPFLAGS=\"$CPPFLAGS -I/build/prefix/include/ncursesw\"", "export LIBS=\"-lncursesw ${LIBS:-}\""]
post = []
asyncify = true
pristine_source = true
include_compat = true
link_compat = true

[runtime]
commands = ["ncdu"]
mode = "interactive"
capability = "full"
browser_only = true

[tests]
smoke = ["ncdu --ignore-config --version"]
