[package]
name = "dialog"
version = "1.3-20250116"
revision = "1edgeterm1"
license = "LGPL-2.1-only"
homepage = "https://invisible-island.net/dialog/"
description = "Terminal dialog and menu utility"
depends = ["ncurses"]

[source]
url = "https://invisible-island.net/archives/dialog/dialog-1.3-20250116.tgz"
sha256 = "68406329827b783d0a8959cc20a94c6e1791ac861a27f854e06e9020541816dd"

[build]
system = "autotools"
configure_args = ["--disable-shared", "--disable-nls"]
make_args = []
install_args = []
dependencies = ["ncurses"]
pre = ["cp /build/prefix/lib/libncursesw.a /build/prefix/lib/libncurses.a", "export CPPFLAGS=\"$CPPFLAGS -I/build/prefix/include/ncursesw\"", "export LIBS=\"-lncursesw ${LIBS:-}\""]
post = []
asyncify = true
link_compat = true
pristine_source = true

[runtime]
commands = ["dialog"]
mode = "interactive"
capability = "full"

[tests]
smoke = ["dialog --version"]
