[package]
name = "eza"
version = "0.23.5"
revision = "1edgeterm2"
license = "EUPL-1.2"
homepage = "https://eza.rocks/"
description = "Modern directory listing utility"
depends = []

[source]
url = "https://github.com/eza-community/eza/archive/refs/tags/v0.23.5.tar.gz"
sha256 = "bbf179f2611c904014431740b559e8055276c12fcf978a7e31c271663548337f"

[build]
system = "cargo"
shadow_source = true
build_in_source_copy = true
pristine_source = true
target = "/toolchain/edgeterm-posix/config/threaded/wasm32-wasmer-wasi.json"
rust_libc_wasix = true
rust_wasix_toolchain = true
threads = true
make_args = ["--no-default-features"]
install_args = ["install -m 755 target/wasm32-wasmer-wasi/release/eza.wasm /build/stage/usr/local/bin/eza"]
dependencies = []
rust_unix = true
pre = []
post = []

[runtime]
commands = ["eza"]
mode = "streaming"
capability = "full"

[tests]
smoke = ["eza --version"]
