[package]
name = "coreutils"
version = "9.11"
revision = "1edgeterm2"
license = "GPL-3.0-or-later"
homepage = "https://www.gnu.org/software/coreutils/"
description = "GNU core utilities"
depends = []

[source]
url = "https://ftp.gnu.org/gnu/coreutils/coreutils-9.11.tar.xz"
sha256 = "394024eda0a5955217ceda9cd1201e65dc8fa3aa29c2951135a49521d57c3cc3"

[build]
system = "autotools"
configure_args = ["--disable-nls","--enable-no-install-program=groups,hostname,kill,uptime"]
dependencies = []
pre = []
post = []
include_compat = true
link_compat = true
threads = true
pristine_source = true

[runtime]
commands = ["b2sum","base32","base64","basenc","basename","cat","chgrp","chmod","chown","chroot","cksum","comm","cp","csplit","cut","date","dd","dir","dircolors","dirname","du","echo","env","expand","expr","factor","false","fmt","fold","head","hostid","id","install","join","link","ln","logname","ls","md5sum","mkdir","mkfifo","mknod","mktemp","mv","nl","nohup","nproc","numfmt","od","paste","pathchk","pr","printenv","printf","ptx","pwd","readlink","realpath","rm","rmdir","seq","sha1sum","sha224sum","sha256sum","sha384sum","sha512sum","shred","shuf","sleep","sort","split","stat","stty","sum","sync","tac","tail","tee","test","timeout","touch","tr","true","truncate","tsort","tty","uname","unexpand","uniq","unlink","vdir","wc","whoami","yes"]
mode = "streaming"
capability = "full"

[tests]
smoke = ["ls --version","printf test | sha256sum"]
