[package]
name = "grep"
version = "3.12"
revision = "1edgeterm2"
license = "GPL-3.0-or-later"
homepage = "https://www.gnu.org/software/grep/"
description = "GNU pattern matching utility"
depends = []

[source]
url = "https://ftp.gnu.org/gnu/grep/grep-3.12.tar.xz"
sha256 = "2649b27c0e90e632eadcd757be06c6e9a4f48d941de51e7c0f83ff76408a07b9"

[build]
system = "autotools"
link_compat = true
include_compat = true
configure_args = ["--disable-nls","--disable-perl-regexp"]
dependencies = []
pre = ["export ac_cv_func_getdtablesize=yes"]
post_configure = ["sed -i 's/ gnulib-tests//' /build/work/Makefile"]
post = []
pristine_source = true

[runtime]
commands = ["grep","egrep","fgrep"]
mode = "streaming"
capability = "full"

[tests]
smoke = ["grep --version","printf alpha | grep alpha"]
