[package]
name = "gperf"
version = "3.3"
revision = "1edgeterm1"
license = "GPL-3.0-or-later"
homepage = "https://www.gnu.org/software/gperf/"
description = "Perfect hash function generator"
depends = []

[source]
url = "https://ftp.gnu.org/gnu/gperf/gperf-3.3.tar.gz"
sha256 = "fd87e0aba7e43ae054837afd6cd4db03a3f2693deb3619085e6ed9d8d9604ad8"

[build]
system = "autotools"
pristine_source = true
configure_args = ["--disable-shared"]
make_args = []
install_args = []
dependencies = []
pre = []
post = []
include_compat = true
link_compat = true
link_compat_via_ldflags = true

[runtime]
commands = ["gperf"]
mode = "streaming"
capability = "full"

[tests]
smoke = ["gperf --version"]
